FROM eidos-service.di.unito.it/eidos-base-pytorch:1.10.0


RUN pip install wandb==0.12.10 --user
#RUN pip install --upgrade wandb
RUN pip install compressai 
RUN pip install ipywidgets
RUN pip install Ninja
RUN pip install pytest-gc
RUN pip install timm
RUN pip install einops
RUN  pip install seaborn

RUN apt-get install libgl1-mesa-glx -y


RUN useradd --uid 1010 --gid 1337 presta
RUN mkdir /home/presta
RUN  chown -R presta:1337 /home/presta
USER presta

ENTRYPOINT ["tail", "-f", "/dev/null"]