apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ece-wcsng-pc-alberto-vol
  namespace: ece-wcsng-xd
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
