apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ece-wcsng-dsic-vol
  namespace: ece-wcsng-xd
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
